// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: SaveFile.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class SaveFile : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(3, Name = @"magic", IsRequired = true)]
    public long Magic { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"active_profile")]
    [global::System.ComponentModel.DefaultValue(0)]
    public int ActiveProfile
    {
        get => __pbn__ActiveProfile ?? 0;
        set => __pbn__ActiveProfile = value;
    }
    public bool ShouldSerializeActiveProfile() => __pbn__ActiveProfile != null;
    public void ResetActiveProfile() => __pbn__ActiveProfile = null;
    private int? __pbn__ActiveProfile;

    [global::ProtoBuf.ProtoMember(5, Name = @"profile")]
    public global::System.Collections.Generic.List<Profile> Profiles { get; } = new global::System.Collections.Generic.List<Profile>();

    [global::ProtoBuf.ProtoContract()]
    public partial class Profile : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"present")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool Present
        {
            get => __pbn__Present ?? false;
            set => __pbn__Present = value;
        }
        public bool ShouldSerializePresent() => __pbn__Present != null;
        public void ResetPresent() => __pbn__Present = null;
        private bool? __pbn__Present;

        [global::ProtoBuf.ProtoMember(2)]
        public Data data { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class Card : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
            public Data data { get; set; }

            [global::ProtoBuf.ProtoContract()]
            public partial class Data : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
                public SaveFile.CardID Id { get; set; } = SaveFile.CardID.IroncladPrototype;

            }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Mission : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
            public Data data { get; set; }

            [global::ProtoBuf.ProtoContract()]
            public partial class Data : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
                public int Id { get; set; }

            }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Cutscene : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
            public SaveFile.CutsceneID Id { get; set; } = SaveFile.CutsceneID.BseProvingGroundBefore;

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Data : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"magic", IsRequired = true)]
            public ulong Magic { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"upgradeProgress")]
            public global::System.Collections.Generic.List<UpgradeProgress> upgradeProgresses { get; } = new global::System.Collections.Generic.List<UpgradeProgress>();

            [global::ProtoBuf.ProtoMember(3, Name = @"missionCompletion")]
            public global::System.Collections.Generic.List<MissionCompletion> missionCompletions { get; } = new global::System.Collections.Generic.List<MissionCompletion>();

            [global::ProtoBuf.ProtoMember(4, Name = @"ownedCard")]
            public global::System.Collections.Generic.List<SaveFile.Profile.Card> ownedCards { get; } = new global::System.Collections.Generic.List<SaveFile.Profile.Card>();

            [global::ProtoBuf.ProtoMember(5, Name = @"unusedCard")]
            public global::System.Collections.Generic.List<SaveFile.Profile.Card> unusedCards { get; } = new global::System.Collections.Generic.List<SaveFile.Profile.Card>();

            [global::ProtoBuf.ProtoMember(8, Name = @"watchedCutscene")]
            public global::System.Collections.Generic.List<WatchedCutscene> watchedCutscenes { get; } = new global::System.Collections.Generic.List<WatchedCutscene>();

            [global::ProtoBuf.ProtoMember(9)]
            public int numberOfDecksEverCreated
            {
                get => __pbn__numberOfDecksEverCreated.GetValueOrDefault();
                set => __pbn__numberOfDecksEverCreated = value;
            }
            public bool ShouldSerializenumberOfDecksEverCreated() => __pbn__numberOfDecksEverCreated != null;
            public void ResetnumberOfDecksEverCreated() => __pbn__numberOfDecksEverCreated = null;
            private int? __pbn__numberOfDecksEverCreated;

            [global::ProtoBuf.ProtoMember(10, Name = @"deck")]
            public global::System.Collections.Generic.List<Deck> Decks { get; } = new global::System.Collections.Generic.List<Deck>();

            [global::ProtoBuf.ProtoMember(11, Name = @"selectedDeck")]
            public global::System.Collections.Generic.List<SelectedDeck> selectedDecks { get; } = new global::System.Collections.Generic.List<SelectedDeck>();

            [global::ProtoBuf.ProtoMember(14, Name = @"unknown14")]
            public global::System.Collections.Generic.List<Unknown14> Unknown14s { get; } = new global::System.Collections.Generic.List<Unknown14>();

            [global::ProtoBuf.ProtoMember(15)]
            [global::System.ComponentModel.DefaultValue(false)]
            public bool hideInstructionCard
            {
                get => __pbn__hideInstructionCard ?? false;
                set => __pbn__hideInstructionCard = value;
            }
            public bool ShouldSerializehideInstructionCard() => __pbn__hideInstructionCard != null;
            public void ResethideInstructionCard() => __pbn__hideInstructionCard = null;
            private bool? __pbn__hideInstructionCard;

            [global::ProtoBuf.ProtoMember(16, Name = @"skirmish")]
            public global::System.Collections.Generic.List<SkirmishResults> Skirmishs { get; } = new global::System.Collections.Generic.List<SkirmishResults>();

            [global::ProtoBuf.ProtoMember(20)]
            [global::System.ComponentModel.DefaultValue(false)]
            public bool completedCampaign
            {
                get => __pbn__completedCampaign ?? false;
                set => __pbn__completedCampaign = value;
            }
            public bool ShouldSerializecompletedCampaign() => __pbn__completedCampaign != null;
            public void ResetcompletedCampaign() => __pbn__completedCampaign = null;
            private bool? __pbn__completedCampaign;

            [global::ProtoBuf.ProtoMember(21, Name = @"secondDeck")]
            public global::System.Collections.Generic.List<SelectedDeck> secondDecks { get; } = new global::System.Collections.Generic.List<SelectedDeck>();

            [global::ProtoBuf.ProtoContract()]
            public partial class UpgradeProgress : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"card", IsRequired = true)]
                public SaveFile.Profile.Card Card { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"progress", IsRequired = true)]
                public int Progress { get; set; }

            }

            [global::ProtoBuf.ProtoContract()]
            public partial class MissionCompletion : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"mission", IsRequired = true)]
                public SaveFile.Profile.Mission Mission { get; set; }

                [global::ProtoBuf.ProtoMember(2)]
                [global::System.ComponentModel.DefaultValue(Objective.BasicWin)]
                public Objective objective
                {
                    get => __pbn__objective ?? Objective.BasicWin;
                    set => __pbn__objective = value;
                }
                public bool ShouldSerializeobjective() => __pbn__objective != null;
                public void Resetobjective() => __pbn__objective = null;
                private Objective? __pbn__objective;

                [global::ProtoBuf.ProtoContract()]
                public enum Objective
                {
                    [global::ProtoBuf.ProtoEnum(Name = @"BASIC_WIN")]
                    BasicWin = 0,
                    [global::ProtoBuf.ProtoEnum(Name = @"STORY_A")]
                    StoryA = 1,
                    [global::ProtoBuf.ProtoEnum(Name = @"STORY_B")]
                    StoryB = 2,
                    [global::ProtoBuf.ProtoEnum(Name = @"PUZZLE")]
                    Puzzle = 3,
                    [global::ProtoBuf.ProtoEnum(Name = @"MULTIPLAYER")]
                    Multiplayer = 4,
                    [global::ProtoBuf.ProtoEnum(Name = @"STORY_C")]
                    StoryC = 5,
                    [global::ProtoBuf.ProtoEnum(Name = @"WAR")]
                    War = 6,
                }

            }

            [global::ProtoBuf.ProtoContract()]
            public partial class WatchedCutscene : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"data", IsRequired = true)]
                public SaveFile.Profile.Cutscene Data { get; set; }

            }

            [global::ProtoBuf.ProtoContract()]
            public partial class Deck : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"index", IsRequired = true)]
                public int Index { get; set; }

                [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
                public Data data { get; set; }

                [global::ProtoBuf.ProtoContract()]
                public partial class Data : global::ProtoBuf.IExtensible
                {
                    private global::ProtoBuf.IExtension __pbn__extensionData;
                    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                    [global::ProtoBuf.ProtoMember(1, Name = @"name", IsRequired = true)]
                    public string Name { get; set; }

                    [global::ProtoBuf.ProtoMember(2, Name = @"card")]
                    public global::System.Collections.Generic.List<SaveFile.Profile.Card> Cards { get; } = new global::System.Collections.Generic.List<SaveFile.Profile.Card>();

                }

            }

            [global::ProtoBuf.ProtoContract()]
            public partial class SelectedDeck : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"present")]
                [global::System.ComponentModel.DefaultValue(false)]
                public bool Present
                {
                    get => __pbn__Present ?? false;
                    set => __pbn__Present = value;
                }
                public bool ShouldSerializePresent() => __pbn__Present != null;
                public void ResetPresent() => __pbn__Present = null;
                private bool? __pbn__Present;

                [global::ProtoBuf.ProtoMember(2, Name = @"selected")]
                [global::System.ComponentModel.DefaultValue(0)]
                public int Selected
                {
                    get => __pbn__Selected ?? 0;
                    set => __pbn__Selected = value;
                }
                public bool ShouldSerializeSelected() => __pbn__Selected != null;
                public void ResetSelected() => __pbn__Selected = null;
                private int? __pbn__Selected;

            }

            [global::ProtoBuf.ProtoContract()]
            public partial class Unknown14 : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"present")]
                [global::System.ComponentModel.DefaultValue(false)]
                public bool Present
                {
                    get => __pbn__Present ?? false;
                    set => __pbn__Present = value;
                }
                public bool ShouldSerializePresent() => __pbn__Present != null;
                public void ResetPresent() => __pbn__Present = null;
                private bool? __pbn__Present;

                [global::ProtoBuf.ProtoMember(2, Name = @"unknown")]
                public int Unknown
                {
                    get => __pbn__Unknown.GetValueOrDefault();
                    set => __pbn__Unknown = value;
                }
                public bool ShouldSerializeUnknown() => __pbn__Unknown != null;
                public void ResetUnknown() => __pbn__Unknown = null;
                private int? __pbn__Unknown;

            }

            [global::ProtoBuf.ProtoContract()]
            public partial class SkirmishResults : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
                public Result result { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"count", IsRequired = true)]
                public int Count { get; set; }

                [global::ProtoBuf.ProtoContract()]
                public enum Result
                {
                    [global::ProtoBuf.ProtoEnum(Name = @"LOSS")]
                    Loss = 0,
                    [global::ProtoBuf.ProtoEnum(Name = @"TIED")]
                    Tied = 1,
                    [global::ProtoBuf.ProtoEnum(Name = @"WIN")]
                    Win = 2,
                }

            }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum CardID
    {
        [global::ProtoBuf.ProtoEnum(Name = @"IRONCLAD_PROTOTYPE")]
        IroncladPrototype = 262145,
        [global::ProtoBuf.ProtoEnum(Name = @"IRONCLAD_POP_UP")]
        IroncladPopUp = 262146,
        [global::ProtoBuf.ProtoEnum(Name = @"IRONCLAD_AUXILIARY")]
        IroncladAuxiliary = 262147,
        [global::ProtoBuf.ProtoEnum(Name = @"IRONCLAD_JETPACK")]
        IroncladJetpack = 262148,
        [global::ProtoBuf.ProtoEnum(Name = @"IRONCLAD_LIGHT")]
        IroncladLight = 262149,
        [global::ProtoBuf.ProtoEnum(Name = @"IRONCLAD_ARMORED")]
        IroncladArmored = 262150,
        [global::ProtoBuf.ProtoEnum(Name = @"IRONCLAD_HEAVY")]
        IroncladHeavy = 262151,
        [global::ProtoBuf.ProtoEnum(Name = @"IRONCLAD_SABOTEUR")]
        IroncladSaboteur = 262154,
        [global::ProtoBuf.ProtoEnum(Name = @"IRONCLAD_OVERPRESSURIZED")]
        IroncladOverpressurized = 262155,
        [global::ProtoBuf.ProtoEnum(Name = @"IRONCLAD_EARTHMOVER")]
        IroncladEarthmover = 262156,
        [global::ProtoBuf.ProtoEnum(Name = @"IRONCLAD_CONCEALED")]
        IroncladConcealed = 262157,
        [global::ProtoBuf.ProtoEnum(Name = @"IRONCLAD_SKIRMISH")]
        IroncladSkirmish = 262158,
        [global::ProtoBuf.ProtoEnum(Name = @"INFANTRY_ZOUAVE")]
        InfantryZouave = 262159,
        [global::ProtoBuf.ProtoEnum(Name = @"INFANTRY_VETERAN_RIFLEMAN")]
        InfantryVeteranRifleman = 262160,
        [global::ProtoBuf.ProtoEnum(Name = @"INFANTRY_RIFLEMAN")]
        InfantryRifleman = 262161,
        [global::ProtoBuf.ProtoEnum(Name = @"INFANTRY_SCOUT")]
        InfantryScout = 262163,
        [global::ProtoBuf.ProtoEnum(Name = @"INFANTRY_RAIDER")]
        InfantryRaider = 262164,
        [global::ProtoBuf.ProtoEnum(Name = @"INFANTRY_MINING_ENGINEER")]
        InfantryMiningEngineer = 262165,
        [global::ProtoBuf.ProtoEnum(Name = @"INFANTRY_SHOTGUN_MERCENARY")]
        InfantryShotgunMercenary = 262166,
        [global::ProtoBuf.ProtoEnum(Name = @"INFANTRY_MUSKET_MERCENARY")]
        InfantryMusketMercenary = 262167,
        [global::ProtoBuf.ProtoEnum(Name = @"INFANTRY_LUMBERJACK")]
        InfantryLumberjack = 262168,
        [global::ProtoBuf.ProtoEnum(Name = @"INFANTRY_SHARPSHOOTER")]
        InfantrySharpshooter = 262169,
        [global::ProtoBuf.ProtoEnum(Name = @"INFANTRY_FOX_RUNNER")]
        InfantryFoxRunner = 262171,
        [global::ProtoBuf.ProtoEnum(Name = @"INFANTRY_ASSAULT_PIONEER")]
        InfantryAssaultPioneer = 262173,
        [global::ProtoBuf.ProtoEnum(Name = @"ARM_MAXS_TRUMPET")]
        ArmMaxsTrumpet = 262175,
        [global::ProtoBuf.ProtoEnum(Name = @"ARM_TRUMPET")]
        ArmTrumpet = 262176,
        [global::ProtoBuf.ProtoEnum(Name = @"ARM_CONGREVE_ROCKET")]
        ArmCongreveRocket = 262177,
        [global::ProtoBuf.ProtoEnum(Name = @"ARM_IMPROVED_MUSKET")]
        ArmImprovedMusket = 262178,
        [global::ProtoBuf.ProtoEnum(Name = @"ARM_RIFLED_MUSKET")]
        ArmRifledMusket = 262179,
        [global::ProtoBuf.ProtoEnum(Name = @"ARM_LIGHT_CANNON")]
        ArmLightCannon = 262180,
        [global::ProtoBuf.ProtoEnum(Name = @"ARM_PISTOL")]
        ArmPistol = 262181,
        [global::ProtoBuf.ProtoEnum(Name = @"ARM_HEAVY_WRENCH")]
        ArmHeavyWrench = 262182,
        [global::ProtoBuf.ProtoEnum(Name = @"ARM_OFFICERS_SABER")]
        ArmOfficersSaber = 262183,
        [global::ProtoBuf.ProtoEnum(Name = @"ARM_CAVALRY_SABER")]
        ArmCavalrySaber = 262184,
        [global::ProtoBuf.ProtoEnum(Name = @"ARM_MINING_DRILL")]
        ArmMiningDrill = 262185,
        [global::ProtoBuf.ProtoEnum(Name = @"ARM_WOOD_CHIPPER")]
        ArmWoodChipper = 262186,
        [global::ProtoBuf.ProtoEnum(Name = @"ARM_GRAPESHOT_CANNON")]
        ArmGrapeshotCannon = 262187,
        [global::ProtoBuf.ProtoEnum(Name = @"ARM_ARROW_BARRAGE_LAUNCHER")]
        ArmArrowBarrageLauncher = 262189,
        [global::ProtoBuf.ProtoEnum(Name = @"ARM_TOMAHAWK")]
        ArmTomahawk = 262190,
        [global::ProtoBuf.ProtoEnum(Name = @"HEAD_BATTLE_FLAG")]
        HeadBattleFlag = 262191,
        [global::ProtoBuf.ProtoEnum(Name = @"HEAD_ZEBULONS_CAT")]
        HeadZebulonsCat = 262192,
        [global::ProtoBuf.ProtoEnum(Name = @"HEAD_MKII_UPGRADE_KIT")]
        HeadMkiiUpgradeKit = 262193,
        [global::ProtoBuf.ProtoEnum(Name = @"HEAD_REDUNDANT_SYSTEMS")]
        HeadRedundantSystems = 262194,
        [global::ProtoBuf.ProtoEnum(Name = @"HEAD_SUPPLEMENTAL_ARMOR")]
        HeadSupplementalArmor = 262195,
        [global::ProtoBuf.ProtoEnum(Name = @"HEAD_CAMOUFLAGE")]
        HeadCamouflage = 262196,
        [global::ProtoBuf.ProtoEnum(Name = @"TACTIC_MANEUVER")]
        TacticManeuver = 262197,
        [global::ProtoBuf.ProtoEnum(Name = @"TACTIC_FIELD_REPAIR")]
        TacticFieldRepair = 262198,
        [global::ProtoBuf.ProtoEnum(Name = @"TACTIC_FULL_STEAM_AHEAD")]
        TacticFullSteamAhead = 262202,
        [global::ProtoBuf.ProtoEnum(Name = @"TACTIC_TACTICAL_ADVANTAGE")]
        TacticTacticalAdvantage = 262203,
        [global::ProtoBuf.ProtoEnum(Name = @"TACTIC_ARTILLERY_BARRAGE")]
        TacticArtilleryBarrage = 262205,
        [global::ProtoBuf.ProtoEnum(Name = @"TACTIC_LOAD_AT_WILL")]
        TacticLoadAtWill = 262206,
        [global::ProtoBuf.ProtoEnum(Name = @"TACTIC_MERCENARY_AMBUSH")]
        TacticMercenaryAmbush = 262210,
        [global::ProtoBuf.ProtoEnum(Name = @"TACTIC_CHAIN_OF_COMMAND")]
        TacticChainOfCommand = 262212,
        [global::ProtoBuf.ProtoEnum(Name = @"TACTIC_DYNAMITE")]
        TacticDynamite = 262214,
        [global::ProtoBuf.ProtoEnum(Name = @"ARM_CARBINE_MUSKET")]
        ArmCarbineMusket = 262216,
        [global::ProtoBuf.ProtoEnum(Name = @"HEAD_SYMBOL_OF_AUTHORITY")]
        HeadSymbolOfAuthority = 262249,
        [global::ProtoBuf.ProtoEnum(Name = @"ARM_ASSAULT_SABER")]
        ArmAssaultSaber = 262250,
        [global::ProtoBuf.ProtoEnum(Name = @"ARM_GATLING_GUN")]
        ArmGatlingGun = 262255,
        [global::ProtoBuf.ProtoEnum(Name = @"IRONCLAD_INDUSTRIAL")]
        IroncladIndustrial = 262262,
        [global::ProtoBuf.ProtoEnum(Name = @"TACTIC_VIN_VITAE")]
        TacticVinVitae = 262263,
        [global::ProtoBuf.ProtoEnum(Name = @"ARM_BANJO")]
        ArmBanjo = 262264,
        [global::ProtoBuf.ProtoEnum(Name = @"ARM_PLOW")]
        ArmPlow = 262265,
        [global::ProtoBuf.ProtoEnum(Name = @"HEAD_TOP_HAT_AND_MONOCLE")]
        HeadTopHatAndMonocle = 262267,
        [global::ProtoBuf.ProtoEnum(Name = @"HEAD_HUNTING_CAP_AND_PIPE")]
        HeadHuntingCapAndPipe = 262268,
        [global::ProtoBuf.ProtoEnum(Name = @"IRONCLAD_REVISED_PROTOTYPE")]
        IroncladRevisedPrototype = 262298,
        [global::ProtoBuf.ProtoEnum(Name = @"TACTIC_FIELD_ADJUSTMENT")]
        TacticFieldAdjustment = 262299,
        [global::ProtoBuf.ProtoEnum(Name = @"IRONCLAD_PROTOTYPE_SHELL")]
        IroncladPrototypeShell = 262311,
        [global::ProtoBuf.ProtoEnum(Name = @"ARM_THE_EMANCIPATOR")]
        ArmTheEmancipator = 262316,
        [global::ProtoBuf.ProtoEnum(Name = @"INFANTRY_DMITRY")]
        InfantryDmitry = 262321,
        [global::ProtoBuf.ProtoEnum(Name = @"IRONCLAD_VISIONARY_SHELL")]
        IroncladVisionaryShell = 262322,
        [global::ProtoBuf.ProtoEnum(Name = @"IRONCLAD_ENTRENCHED_SHELL")]
        IroncladEntrenchedShell = 262323,
        [global::ProtoBuf.ProtoEnum(Name = @"IRONCLAD_VICTORY_SHELL")]
        IroncladVictoryShell = 262324,
        [global::ProtoBuf.ProtoEnum(Name = @"IRONCLAD_ONSLAUGHT_SHELL")]
        IroncladOnslaughtShell = 262325,
        [global::ProtoBuf.ProtoEnum(Name = @"IRONCLAD_GENERATOR_SHELL")]
        IroncladGeneratorShell = 262326,
        [global::ProtoBuf.ProtoEnum(Name = @"ARM_THE_MOTIVATOR")]
        ArmTheMotivator = 262327,
        [global::ProtoBuf.ProtoEnum(Name = @"ARM_ANTI_MATERIEL_RIFLE")]
        ArmAntiMaterielRifle = 262328,
        [global::ProtoBuf.ProtoEnum(Name = @"HEAD_DESPERADO_HAT")]
        HeadDesperadoHat = 262329,
        [global::ProtoBuf.ProtoEnum(Name = @"ARM_RAY_OF_TERROR")]
        ArmRayOfTerror = 262334,
        [global::ProtoBuf.ProtoEnum(Name = @"IRONCLAD_DMITRY")]
        IroncladDmitry = 262347,
        [global::ProtoBuf.ProtoEnum(Name = @"TACTIC_DEFENSIVE_POSTURE")]
        TacticDefensivePosture = 262348,
        [global::ProtoBuf.ProtoEnum(Name = @"TACTIC_ESCAPE_PLAN")]
        TacticEscapePlan = 262349,
        [global::ProtoBuf.ProtoEnum(Name = @"HEAD_REINFORCED_FRAME")]
        HeadReinforcedFrame = 262350,
        [global::ProtoBuf.ProtoEnum(Name = @"IRONCLAD_LIGHT_MARCHEUR")]
        IroncladLightMarcheur = 262362,
        [global::ProtoBuf.ProtoEnum(Name = @"IRONCLAD_BARRAGE_MARCHEUR")]
        IroncladBarrageMarcheur = 262363,
        [global::ProtoBuf.ProtoEnum(Name = @"IRONCLAD_RAMPART_MARCHEUR")]
        IroncladRampartMarcheur = 262364,
        [global::ProtoBuf.ProtoEnum(Name = @"INFANTRY_VOLTIGEUR")]
        InfantryVoltigeur = 262365,
        [global::ProtoBuf.ProtoEnum(Name = @"INFANTRY_SOUS_LIEUTENANT")]
        InfantrySousLieutenant = 262366,
        [global::ProtoBuf.ProtoEnum(Name = @"INFANTRY_ZOUAVE_ARMORED")]
        InfantryZouaveArmored = 262367,
        [global::ProtoBuf.ProtoEnum(Name = @"INFANTRY_CANNONEER")]
        InfantryCannoneer = 262368,
        [global::ProtoBuf.ProtoEnum(Name = @"ARM_MITRAILLEUSE")]
        ArmMitrailleuse = 262369,
        [global::ProtoBuf.ProtoEnum(Name = @"ARM_SABRE")]
        ArmSabre = 262370,
        [global::ProtoBuf.ProtoEnum(Name = @"ARM_EPEE")]
        ArmEpee = 262371,
        [global::ProtoBuf.ProtoEnum(Name = @"ARM_DRAGON")]
        ArmDragon = 262372,
        [global::ProtoBuf.ProtoEnum(Name = @"HEAD_CUIRASSIERS_HELMENT")]
        HeadCuirassiersHelment = 262373,
        [global::ProtoBuf.ProtoEnum(Name = @"TACTIC_SWIFT_ASSAULT")]
        TacticSwiftAssault = 262374,
        [global::ProtoBuf.ProtoEnum(Name = @"TACTIC_RETREAT")]
        TacticRetreat = 262375,
        [global::ProtoBuf.ProtoEnum(Name = @"IRONCLAD_EISENWALKER")]
        IroncladEisenwalker = 262376,
        [global::ProtoBuf.ProtoEnum(Name = @"IRONCLAD_JAGERWALKER")]
        IroncladJagerwalker = 262377,
        [global::ProtoBuf.ProtoEnum(Name = @"IRONCLAD_BLITZWALKER")]
        IroncladBlitzwalker = 262378,
        [global::ProtoBuf.ProtoEnum(Name = @"INFANTRY_GRENADIER")]
        InfantryGrenadier = 262379,
        [global::ProtoBuf.ProtoEnum(Name = @"INFANTRY_FIELD_MEDIC")]
        InfantryFieldMedic = 262380,
        [global::ProtoBuf.ProtoEnum(Name = @"INFANTRY_JAGER")]
        InfantryJager = 262381,
        [global::ProtoBuf.ProtoEnum(Name = @"INFANTRY_CONSCRIPT")]
        InfantryConscript = 262382,
        [global::ProtoBuf.ProtoEnum(Name = @"ARM_BREECH_LOADING_CANNON")]
        ArmBreechLoadingCannon = 262383,
        [global::ProtoBuf.ProtoEnum(Name = @"ARM_NEEDLE_RIFLE")]
        ArmNeedleRifle = 262384,
        [global::ProtoBuf.ProtoEnum(Name = @"ARM_SPEAR")]
        ArmSpear = 262385,
        [global::ProtoBuf.ProtoEnum(Name = @"ARM_FLUGELHORN")]
        ArmFlugelhorn = 262386,
        [global::ProtoBuf.ProtoEnum(Name = @"HEAD_CAVALRY_HELMET")]
        HeadCavalryHelmet = 262387,
        [global::ProtoBuf.ProtoEnum(Name = @"TACTIC_FIRING_LINE")]
        TacticFiringLine = 262388,
        [global::ProtoBuf.ProtoEnum(Name = @"ARM_INFERNO_CANNON")]
        ArmInfernoCannon = 262401,
        [global::ProtoBuf.ProtoEnum(Name = @"INFANTRY_EAGLE_WARROR")]
        InfantryEagleWarror = 262402,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum CutsceneID
    {
        [global::ProtoBuf.ProtoEnum(Name = @"BSE_PROVING_GROUND_BEFORE")]
        BseProvingGroundBefore = 524289,
        [global::ProtoBuf.ProtoEnum(Name = @"BSE_PROVING_GROUND_AFTER")]
        BseProvingGroundAfter = 524290,
        [global::ProtoBuf.ProtoEnum(Name = @"NORTH_ALBANY_RAILYARD")]
        NorthAlbanyRailyard = 524291,
        [global::ProtoBuf.ProtoEnum(Name = @"BEACON_PARK_RAILYARD_BEFORE")]
        BeaconParkRailyardBefore = 524292,
        [global::ProtoBuf.ProtoEnum(Name = @"BEACON_PARK_RAILYARD_AFTER")]
        BeaconParkRailyardAfter = 524293,
        [global::ProtoBuf.ProtoEnum(Name = @"THE_STATE_DINING_ROOM")]
        TheStateDiningRoom = 524296,
        [global::ProtoBuf.ProtoEnum(Name = @"THE_NORTH_LAWN_BEFORE")]
        TheNorthLawnBefore = 524297,
        [global::ProtoBuf.ProtoEnum(Name = @"THE_NORTH_LAWN_AFTER")]
        TheNorthLawnAfter = 524298,
        [global::ProtoBuf.ProtoEnum(Name = @"GREAT_DISMAL_SWAMP_BEFORE")]
        GreatDismalSwampBefore = 524299,
        [global::ProtoBuf.ProtoEnum(Name = @"GREAT_DISMAL_SWAMP_AFTER")]
        GreatDismalSwampAfter = 524300,
        [global::ProtoBuf.ProtoEnum(Name = @"CHARLESTON_HARBOUR_BEFORE")]
        CharlestonHarbourBefore = 524301,
        [global::ProtoBuf.ProtoEnum(Name = @"CHARLESTON_HARBOUR_AFTER")]
        CharlestonHarbourAfter = 524302,
        [global::ProtoBuf.ProtoEnum(Name = @"ABANDONED_WAREHOUSE_BEFORE")]
        AbandonedWarehouseBefore = 524303,
        [global::ProtoBuf.ProtoEnum(Name = @"ABANDONED_WAREHOUSE_AFTER")]
        AbandonedWarehouseAfter = 524304,
        [global::ProtoBuf.ProtoEnum(Name = @"TALLADEGA_FOREST_BEFORE")]
        TalladegaForestBefore = 524305,
        [global::ProtoBuf.ProtoEnum(Name = @"TALLADEGA_FOREST_AFTER")]
        TalladegaForestAfter = 524306,
        [global::ProtoBuf.ProtoEnum(Name = @"NORTH_BOULEVARD_BEFORE")]
        NorthBoulevardBefore = 524307,
        [global::ProtoBuf.ProtoEnum(Name = @"NORTH_BOULEVARD_AFTER")]
        NorthBoulevardAfter = 524308,
        [global::ProtoBuf.ProtoEnum(Name = @"FACTORY_FORT_ENDICOTT_BEFORE")]
        FactoryFortEndicottBefore = 524309,
        [global::ProtoBuf.ProtoEnum(Name = @"FACTORY_FORT_ENDICOTT_AFTER")]
        FactoryFortEndicottAfter = 524310,
        [global::ProtoBuf.ProtoEnum(Name = @"MAIN_STREET_BEFORE")]
        MainStreetBefore = 524311,
        [global::ProtoBuf.ProtoEnum(Name = @"MAIN_STREET_AFTER")]
        MainStreetAfter = 524312,
        [global::ProtoBuf.ProtoEnum(Name = @"MADAME_MILLIES_RANCH_BEFORE")]
        MadameMilliesRanchBefore = 524315,
        [global::ProtoBuf.ProtoEnum(Name = @"MADAME_MILLIES_RANCH_AFTER")]
        MadameMilliesRanchAfter = 524316,
        [global::ProtoBuf.ProtoEnum(Name = @"HASSAYAMPA_GOLD_MINE_BEFORE")]
        HassayampaGoldMineBefore = 524317,
        [global::ProtoBuf.ProtoEnum(Name = @"HASSAYAMPA_GOLD_MINE_AFTER")]
        HassayampaGoldMineAfter = 524318,
        [global::ProtoBuf.ProtoEnum(Name = @"LAS_VEGAS_STEAMWORKS_BEFORE")]
        LasVegasSteamworksBefore = 524319,
        [global::ProtoBuf.ProtoEnum(Name = @"LAS_VEGAS_STEAMWORKS_AFTER")]
        LasVegasSteamworksAfter = 524320,
        [global::ProtoBuf.ProtoEnum(Name = @"MOJAVE_DESERT")]
        MojaveDesert = 524327,
        [global::ProtoBuf.ProtoEnum(Name = @"SAN_BRUNO_MOUNTAIN_BEFORE")]
        SanBrunoMountainBefore = 524321,
        [global::ProtoBuf.ProtoEnum(Name = @"SAN_BRUNO_MOUNTAIN_AFTER")]
        SanBrunoMountainAfter = 524322,
        [global::ProtoBuf.ProtoEnum(Name = @"BALDWIN_LOGGING_CAMP_BEFORE")]
        BaldwinLoggingCampBefore = 524323,
        [global::ProtoBuf.ProtoEnum(Name = @"BALDWIN_LOGGING_CAMP_AFTER")]
        BaldwinLoggingCampAfter = 524324,
        [global::ProtoBuf.ProtoEnum(Name = @"PORT_OF_SEATTLE_BEFORE")]
        PortOfSeattleBefore = 524325,
        [global::ProtoBuf.ProtoEnum(Name = @"PORT_OF_SEATTLE_AFTER")]
        PortOfSeattleAfter = 524326,
        [global::ProtoBuf.ProtoEnum(Name = @"EPILOGUE")]
        Epilogue = 524328,
        [global::ProtoBuf.ProtoEnum(Name = @"PORT_OF_GALVESTON")]
        PortOfGalveston = 524330,
        [global::ProtoBuf.ProtoEnum(Name = @"FORT_PHANTOM_RIDGE_FIRST")]
        FortPhantomRidgeFirst = 524331,
        [global::ProtoBuf.ProtoEnum(Name = @"PAKOTAS_VILLAGE_FIRST")]
        PakotasVillageFirst = 524332,
        [global::ProtoBuf.ProtoEnum(Name = @"PAKOTAS_VILLAGE_SECOND")]
        PakotasVillageSecond = 524333,
        [global::ProtoBuf.ProtoEnum(Name = @"HASSAYAMPA_GOLD_MINE_DMITRY")]
        HassayampaGoldMineDmitry = 524334,
        [global::ProtoBuf.ProtoEnum(Name = @"SEVENBARK_MANOR_BEFORE")]
        SevenbarkManorBefore = 524335,
        [global::ProtoBuf.ProtoEnum(Name = @"SEVENBARK_MANOR_AFTER")]
        SevenbarkManorAfter = 524336,
        [global::ProtoBuf.ProtoEnum(Name = @"LAS_VEGA_STEAMWORKS_DMITRY_BEFORE")]
        LasVegaSteamworksDmitryBefore = 524337,
        [global::ProtoBuf.ProtoEnum(Name = @"LAS_VEGA_STEAMWORKS_DMITRY_AFTER")]
        LasVegaSteamworksDmitryAfter = 524338,
        [global::ProtoBuf.ProtoEnum(Name = @"FORT_PHANTOM_RIDGE_SECOND")]
        FortPhantomRidgeSecond = 524339,
        [global::ProtoBuf.ProtoEnum(Name = @"BLOOD_AND_IRONCLADS_INTRO")]
        BloodAndIroncladsIntro = 524340,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
